### ISSUE TITLE
Allow fallback to the old naming pattern for services

### ISSUE THREAD

**Issue by vdombrovski** [open-io/ansible-role-openio-gridinit#10]
#### Issue type

Enhancement

#### Description

The newly introduced "nested" pattern will raise compatibility issues with old systems.

See the related gridinit issue: https://github.com/open-io/gridinit/issues/15

Currently, there is no way to handle both naming patterns in `gridinit`:
- NEW: $CONF_PATH/[NS]/[service]
- OLD: $CONF_PATH/[NS]-[service]

Until the issue is resolved, I think it would be best to fallback (at least optionally) to the old syntax for this role, to avoid breaking changes with existing setups.

**Comment by racciari** [comment]
Should be fixed in #13 
Thanks.
